# Generated by Django 2.2.7 on 2019-11-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='email address'),
        ),
    ]
