# Generated by Django 2.2.7 on 2019-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
    ]
