# Generated by Django 2.2.7 on 2019-11-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=70)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image", models.URLField(blank=True, null=True)),
                ("reviewScore", models.FloatField(default=0.0)),
            ],
        )
    ]
