# Generated by Django 2.2.7 on 2019-11-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("product", "0001_initial")]

    operations = [
        migrations.RenameModel(old_name="Client", new_name="Product")
    ]
